# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 800)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.group_right = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_right.sizePolicy().hasHeightForWidth())
        self.group_right.setSizePolicy(sizePolicy)
        self.group_right.setMinimumSize(QtCore.QSize(120, 65))
        self.group_right.setMaximumSize(QtCore.QSize(100, 73))
        self.group_right.setTitle("")
        self.group_right.setObjectName("group_right")
        self.button_open_dialog = QtWidgets.QPushButton(self.group_right)
        self.button_open_dialog.setGeometry(QtCore.QRect(0, 30, 117, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_open_dialog.sizePolicy().hasHeightForWidth())
        self.button_open_dialog.setSizePolicy(sizePolicy)
        self.button_open_dialog.setMinimumSize(QtCore.QSize(117, 0))
        self.button_open_dialog.setObjectName("button_open_dialog")
        self.gridLayout.addWidget(self.group_right, 1, 3, 1, 1)
        self.group_below = QtWidgets.QGroupBox(self.central_widget)
        self.group_below.setMinimumSize(QtCore.QSize(0, 35))
        self.group_below.setTitle("")
        self.group_below.setObjectName("group_below")
        self.button_delete_book = QtWidgets.QPushButton(self.group_below)
        self.button_delete_book.setGeometry(QtCore.QRect(790, 0, 117, 34))
        self.button_delete_book.setMinimumSize(QtCore.QSize(110, 0))
        self.button_delete_book.setMaximumSize(QtCore.QSize(117, 16777215))
        self.button_delete_book.setObjectName("button_delete_book")
        self.button_sell_book = QtWidgets.QPushButton(self.group_below)
        self.button_sell_book.setGeometry(QtCore.QRect(910, 0, 110, 34))
        self.button_sell_book.setMinimumSize(QtCore.QSize(110, 0))
        self.button_sell_book.setMaximumSize(QtCore.QSize(84, 16777215))
        self.button_sell_book.setObjectName("button_sell_book")
        self.button_edit = QtWidgets.QPushButton(self.group_below)
        self.button_edit.setGeometry(QtCore.QRect(0, 0, 141, 34))
        self.button_edit.setObjectName("button_edit")
        self.gridLayout.addWidget(self.group_below, 3, 2, 1, 1)
        self.table_inventory = QtWidgets.QTableView(self.central_widget)
        self.table_inventory.setSortingEnabled(True)
        self.table_inventory.setObjectName("table_inventory")
        self.gridLayout.addWidget(self.table_inventory, 1, 2, 1, 1)
        self.line_search = QtWidgets.QLineEdit(self.central_widget)
        self.line_search.setObjectName("line_search")
        self.gridLayout.addWidget(self.line_search, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1168, 27))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_file = QtWidgets.QMenu(self.menu_bar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.action_open_dialog = QtWidgets.QAction(MainWindow)
        self.action_open_dialog.setObjectName("action_open_dialog")
        self.action_search = QtWidgets.QAction(MainWindow)
        self.action_search.setObjectName("action_search")
        self.action_delete_book = QtWidgets.QAction(MainWindow)
        self.action_delete_book.setObjectName("action_delete_book")
        self.action_edit_book = QtWidgets.QAction(MainWindow)
        self.action_edit_book.setObjectName("action_edit_book")
        self.action_sell_book = QtWidgets.QAction(MainWindow)
        self.action_sell_book.setObjectName("action_sell_book")
        self.menu_bar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        self.button_edit.clicked.connect(MainWindow.edit_book) # type: ignore
        self.button_delete_book.clicked.connect(MainWindow.delete_book) # type: ignore
        self.button_sell_book.clicked.connect(MainWindow.sell_book) # type: ignore
        self.button_open_dialog.clicked.connect(MainWindow.open_dialog) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_open_dialog.setText(_translate("MainWindow", "Lägg till ny/Sälj"))
        self.button_delete_book.setText(_translate("MainWindow", "Ta bort markerad"))
        self.button_sell_book.setText(_translate("MainWindow", "Sälj markerad"))
        self.button_edit.setText(_translate("MainWindow", "Redigera markerad"))
        self.line_search.setPlaceholderText(_translate("MainWindow", "Sök"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.action_open_dialog.setText(_translate("MainWindow", "Open dialog"))
        self.action_search.setText(_translate("MainWindow", "search"))
        self.action_delete_book.setText(_translate("MainWindow", "delete_book"))
        self.action_edit_book.setText(_translate("MainWindow", "edit_book"))
        self.action_sell_book.setText(_translate("MainWindow", "sell_book"))
